// AUTO-GENERATED from BOOM Provider API + Aria cost_floors + PriceLabs snapshot.
// Regenerate: python3.12 scripts/regenerate-listings-from-boom.py

export type AreaSlug = "regents-park-marylebone" | "old-street-shoreditch" | "hackney" | "islington-angel" | "kensington-hammersmith" | "fitzrovia-mayfair" | "barbican-farringdon" | "borough-pimlico" | "little-venice-maida-vale";

export type Listing = { slug: string; title: string; area: AreaSlug; areaLabel: string; bedrooms: number; bathrooms: number; maxGuests: number; sizeSqm: number; fromGbpPerNight: number; shortDescription: string; longDescription: string; amenities: string[]; heroImage: string; gallery: string[]; latitude?: number; longitude?: number; postcode?: string; boomListingId?: string; bookingUrl?: string; };

export type Location = { slug: AreaSlug; label: string; shortLabel: string; propertyCountApprox: number; description: string; whyStayHere: string; nearbyHighlights: string[]; transport: string[]; latitude: number; longitude: number; heroImage: string; };

export const LOCATIONS: Location[] = [
  {
    slug: "old-street-shoreditch",
    label: "Old Street & Shoreditch",
    shortLabel: "Old Street & Shoreditch",
    propertyCountApprox: 5,
    description: "London's creative and tech corridor. Silicon Roundabout, Spitalfields, Brick Lane. Design-led apartments at the seam of finance and east-end street culture.",
    whyStayHere: "Walk to your meeting in the City, then bar-hop through Shoreditch the same evening. Suits founders, designers, consultants on short engagements.",
    nearbyHighlights: ["Spitalfields Market and Old Spitalfields antiques", "Brick Lane (Sunday market, curry mile, vintage)", "Boxpark Shoreditch and Box Hall", "The Curtain rooftop and Shoreditch House (members only)", "Whitechapel Gallery"],
    transport: ["Old Street (Northern)", "Liverpool Street (Central, Circle, Elizabeth, H&C, Metropolitan, National Rail)", "Shoreditch High Street (Overground)", "Hoxton (Overground)"],
    latitude: 51.5253,
    longitude: -0.0801,
    heroImage: "/locations/old-street-shoreditch.jpg",
  },
  {
    slug: "hackney",
    label: "Hackney",
    shortLabel: "Hackney",
    propertyCountApprox: 1,
    description: "East London's most characterful corner — Columbia Road flowers, Broadway Market, and Victoria Park. Brick terraces, independent cafés, and Sunday markets on the doorstep.",
    whyStayHere: "Slow weekends, flower markets and canalside walks, with Liverpool Street and the City a short hop away. Suits leisure stays and longer creative visits.",
    nearbyHighlights: ["Columbia Road Flower Market (Sundays)", "Broadway Market and London Fields", "Victoria Park", "Regent's Canal towpath", "Brick Lane and Spitalfields nearby"],
    transport: ["Bethnal Green (Central)", "Cambridge Heath (Overground)", "Hoxton (Overground)", "Liverpool Street (Central, Circle, Elizabeth, National Rail)"],
    latitude: 51.5276,
    longitude: -0.069,
    heroImage: "/locations/hackney.jpg",
  },
  {
    slug: "islington-angel",
    label: "Islington & Angel",
    shortLabel: "Islington & Angel",
    propertyCountApprox: 1,
    description: "Upper Street's restaurants and theatres, the antiques of Camden Passage, and elegant Georgian squares. Polished and leafy, with Angel minutes from the City and King's Cross.",
    whyStayHere: "Dining, theatre and antiques on the doorstep, with fast links to King's Cross and the City. Suits couples, theatre-goers, and business stays.",
    nearbyHighlights: ["Upper Street dining and the Almeida Theatre", "Camden Passage antiques market", "Sadler's Wells", "Regent's Canal and Granary Square", "Chapel Market"],
    transport: ["Angel (Northern)", "Highbury & Islington (Victoria, Overground)", "King's Cross St Pancras (six lines + Eurostar)", "Essex Road (Overground)"],
    latitude: 51.5362,
    longitude: -0.1033,
    heroImage: "/locations/islington-angel.jpg",
  },
  {
    slug: "borough-pimlico",
    label: "Borough & Pimlico",
    shortLabel: "Borough & Pimlico",
    propertyCountApprox: 1,
    description: "South Bank food culture and Pimlico's Regency streets. Walk to Tate Modern, the Globe, and Borough Market for breakfast.",
    whyStayHere: "Weekend leisure stays, foodie trips, family-friendly walks along the river. Quieter than the West End, ten minutes from Waterloo.",
    nearbyHighlights: ["Borough Market (one of London's best food markets)", "Tate Modern and the Tate Britain", "The Shard and the Globe", "Westminster, Lambeth Palace, Vauxhall Pleasure Gardens", "Battersea Power Station"],
    transport: ["Borough (Northern)", "London Bridge (Jubilee, Northern, National Rail)", "Pimlico (Victoria)", "Vauxhall (Victoria, National Rail)"],
    latitude: 51.497,
    longitude: -0.1057,
    heroImage: "/locations/borough-pimlico.jpg",
  },
];

export const LISTINGS: Listing[] = [
  {
    slug: "borough-pimlico-163-new-kent-rd-e4e562",
    title: "163 New Kent Road · 1-bed",
    area: "borough-pimlico",
    areaLabel: "Borough & Pimlico",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 125,
    shortDescription: "A 1-bed apartment walkable to Borough Market, the Tate Modern, and the Thames.",
    longDescription: "A 1-bed apartment walkable to Borough Market, the Tate Modern, and the Thames.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Self check-in", "Linen + towels", "Housekeeping on request", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750848039/tenants/NourNest/listings/163NewKentRd-Lukasz-main/pictures/WhatsApp_Image_2025-05-23_at_00.28.18_522c1337_riltic.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750848039/tenants/NourNest/listings/163NewKentRd-Lukasz-main/pictures/WhatsApp_Image_2025-05-23_at_00.28.18_522c1337_riltic.png"],
    latitude: 51.4945478,
    longitude: -0.0923599,
    postcode: "SE1 4AG",
    boomListingId: "e4e56230-34fb-4410-b6e0-de0dd06e51a3",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13535",
  },
  {
    slug: "old-street-shoreditch-hackney-1b-bfb561",
    title: "Hackney Flat 1B · 1-bed",
    area: "hackney",
    areaLabel: "Hackney",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 125,
    shortDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Self check-in", "Linen + towels", "Housekeeping on request", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750682205/tenants/NourNest/listings/Hackney1B-Szymon-Main/pictures/IMG-20250421-WA0184_yiho9t.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750682205/tenants/NourNest/listings/Hackney1B-Szymon-Main/pictures/IMG-20250421-WA0184_yiho9t.png"],
    latitude: 51.52763400000001,
    longitude: -0.07689770000000001,
    postcode: "E2 7NX",
    boomListingId: "bfb561ed-c235-4ea5-84f0-5e002a10da28",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13548",
  },
  {
    slug: "old-street-shoreditch-old-st-flat-3-1523cb",
    title: "Old Street Flat 3 · 1-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Self check-in", "Linen + towels", "Housekeeping on request", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1751291705/tenants/NourNest/listings/OldStFlat3-Szymon-main/pictures/IMG-20250513-WA0055_p8psjl.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1751291705/tenants/NourNest/listings/OldStFlat3-Szymon-main/pictures/IMG-20250513-WA0055_p8psjl.png"],
    latitude: 51.5270111,
    longitude: -0.08012989999999999,
    postcode: "EC1V 9LT",
    boomListingId: "1523cbce-f736-41e4-87d8-77516c606fc4",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13540",
  },
  {
    slug: "old-street-shoreditch-liverpool-rd-4c5f09",
    title: "Liverpool Road · 1-bed",
    area: "islington-angel",
    areaLabel: "Islington & Angel",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 125,
    shortDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Self check-in", "Linen + towels", "Housekeeping on request", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1750776502/tenants/NourNest/listings/LiverpoolRd-Szymon-BDCmain/pictures/IMG-20250512-WA0591_xkzpsj.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1750776502/tenants/NourNest/listings/LiverpoolRd-Szymon-BDCmain/pictures/IMG-20250512-WA0591_xkzpsj.png"],
    latitude: 51.5449564,
    longitude: -0.1078811,
    postcode: "N1 1NP",
    boomListingId: "4c5f09e5-6625-48ca-a613-82360732e345",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13533",
  },
  {
    slug: "old-street-shoreditch-old-st-flat-1-7a92a4",
    title: "Old Street Flat 1 · 1-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Self check-in", "Linen + towels", "Housekeeping on request", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1752858980/tenants/NourNest/listings/OldStFlat1-Szymon-main/pictures/IMG-20250421-WA0151_ftx7ks.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1752858980/tenants/NourNest/listings/OldStFlat1-Szymon-main/pictures/IMG-20250421-WA0151_ftx7ks.png"],
    latitude: 51.5270111,
    longitude: -0.08012989999999999,
    postcode: "EC1V 9LT",
    boomListingId: "7a92a4ad-75ea-4bc7-8f60-89b3de471ab2",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13538",
  },
  {
    slug: "old-street-shoreditch-old-st-flat-2-362ecb",
    title: "Old Street Flat 2 · 1-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 150,
    shortDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Self check-in", "Linen + towels", "Housekeeping on request", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1752859070/tenants/NourNest/listings/OldStFlat2-Szymon-main/pictures/IMG-20250428-WA0278_jgk6of.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1752859070/tenants/NourNest/listings/OldStFlat2-Szymon-main/pictures/IMG-20250428-WA0278_jgk6of.png"],
    latitude: 51.527526,
    longitude: -0.0802534,
    postcode: "EC1V 9LT",
    boomListingId: "362ecb60-81a3-41ca-820c-4e24a63e229b",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13539",
  },
  {
    slug: "old-street-shoreditch-shoreditch-flat-5-a820ac",
    title: "Shoreditch Flat 5 · 4-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 4,
    bathrooms: 3,
    maxGuests: 10,
    sizeSqm: 0,
    fromGbpPerNight: 285,
    shortDescription: "A 4-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 4-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Self check-in", "Linen + towels", "Housekeeping on request", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1779883229/tenants/NourNest/listingsShoreditchflat5-Szymonpictures/ChatGPT_Image_May_26_2026_06_00_31_PM_u2qt8x.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1779883229/tenants/NourNest/listingsShoreditchflat5-Szymonpictures/ChatGPT_Image_May_26_2026_06_00_31_PM_u2qt8x.png"],
    latitude: 51.52269039999999,
    longitude: -0.0780659,
    postcode: "E1 6PJ",
    boomListingId: "a820acb7-3a1e-4ed7-bd60-30b9d10dbe61",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/26216",
  },
  {
    slug: "old-street-shoreditch-old-st-basement-620fc3",
    title: "Old Street Basement · 1-bed",
    area: "old-street-shoreditch",
    areaLabel: "Old Street & Shoreditch",
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    sizeSqm: 0,
    fromGbpPerNight: 125,
    shortDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    longDescription: "A 1-bed apartment minutes from Spitalfields Market, Old Street, and the City.",
    amenities: ["Wi-Fi", "Smart TV", "Fitted kitchen", "Washer-dryer", "Self check-in", "Linen + towels", "Housekeeping on request", "All bills included"],
    heroImage: "https://res.cloudinary.com/do4tedxg6/image/upload/v1753456169/tenants/NourNest/listings/OldStBasement-Lukasz-main/pictures/IMG-20250513-WA0035_el0xl1.png",
    gallery: ["https://res.cloudinary.com/do4tedxg6/image/upload/v1753456169/tenants/NourNest/listings/OldStBasement-Lukasz-main/pictures/IMG-20250513-WA0035_el0xl1.png"],
    latitude: 51.527526,
    longitude: -0.0802534,
    postcode: "EC1V 9LT",
    boomListingId: "620fc3f0-1a2d-42c0-bfe1-631334a56d02",
    bookingUrl: "https://nournestapartments.bookingsboom.com/listing/13537",
  },
];

export function listingsByArea(area: AreaSlug): Listing[] { return LISTINGS.filter((l) => l.area === area); }
export function getListing(slug: string): Listing | undefined { return LISTINGS.find((l) => l.slug === slug); }
export function getLocation(slug: AreaSlug): Location | undefined { return LOCATIONS.find((l) => l.slug === slug); }